name = "Minestuck"
author = "Minestuck maintainers, Maow"
version = "2026.05.31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "787dfd472bea1bdc96afd1f3e85b2ffe294c5eb93b7d8915f2b263b2b9efd58a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
