name = "Minestuck"
author = "Minestuck maintainers, Maow"
version = "2026.05.31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8fb948996c6259ddda966a274ece143dea2fb96bdc0fe6b6f2e0aafc8a1e037"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
